version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyectorazorproductos
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=RazorMvcProductosDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;Encrypt=False;"

volumes:
  sqlserver_data: