name: .NET CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar paquetes
        run: dotnet restore

      - name: Compilar
        run: dotnet build --configuration Release --no-restore

      - name: Ejecutar pruebas
        run: dotnet test --configuration Release --no-build --verbosity normal